services:
  proxy:
    build: .
    container_name: proxy-app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./logs:/logs
    environment:
      - LOG_DIR=/logs
      - LISTEN=${LISTEN}
      - SERVERS=${SERVERS}
    restart: always